name: Setup tfcmt
description: Setup tfcmt and github-comment
runs:
  using: "composite"
  steps:
    - run: curl -LO https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.0.0/tfcmt_linux_amd64.tar.gz
      shell: bash

    - run: echo '639852873597bcfbd0f8b5e708163c0f144c335e25163dde9b3e633ea066e230  tfcmt_linux_amd64.tar.gz' | sha256sum --check
      shell: bash

    - run: sudo tar -C /usr/bin/ -zxf tfcmt_linux_amd64.tar.gz
      shell: bash

    - run: curl -LO https://github.com/suzuki-shunsuke/github-comment/releases/download/v4.1.0/github-comment_4.1.0_linux_amd64.tar.gz
      shell: bash

    - run: echo 'aa1df14b64d2e871fd395f63b10ca1c4322fb16dc8decca8fd9e67d360cefc79  github-comment_4.1.0_linux_amd64.tar.gz' | sha256sum --check
      shell: bash

    - run: sudo tar -C /usr/bin/ -zxf github-comment_4.1.0_linux_amd64.tar.gz
      shell: bash
